### ISSUE TITLE
Which Ubuntu version is supported?

### ISSUE THREAD

**Issue by AlexanderFabisch** [ilidar-tof/iviewer#1]
I cannot run the iviewer at the moment because I do not have the correct version of either libgw and opencv (Ubuntu 22.04) or libstdc++ (Ubuntu 20.04). Which version of Ubuntu was the viewer built for / with?

**Comment by JEONG-Ingyo** [comment]
Hello.
We have built the software on Ubuntu 20.04 and libstdc++6 version 13.1.0-8ubuntu1~20.04.2. Please check the version of libstdc++ is as follows;

```bash
$ dpkg-query -W -f='${Version}\n' libstdc++6
13.1.0-8ubuntu1~20.04.2

**Comment by JEONG-Ingyo** [comment]
Here's an additional reminder.
This software is currently developed exclusively for iTFS iLidar-ToF products.
For APIs for iLidar products that are triangulation-based 2D LiDAR, please refer to the following page.
[https://github.com/hybo-ilidar](https://github.com/hybo-ilidar)

**Comment by AlexanderFabisch** [comment]
Thanks for the quick reply!
